In [ ]:
#Importing libraries
#!pip install tensorflow
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential
from sklearn.metrics import classification_report
import warnings
warnings.filterwarnings('ignore')

In [ ]:
#Load the dataset
df = pd.read_csv('https://raw.githubusercontent.com/Shrikrishna-jadhavar/Data-Science-Material/main/Dataset/Churn_Modelling.csv')
df

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9996,15606229,Obijiaku,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,9997,15569892,Johnstone,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,9998,15584532,Liu,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,9999,15682355,Sabbatini,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,10000,15628319,Walker,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
df.drop(columns=['RowNumber','CustomerId','Surname'], inplace=True)

In [ ]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

# Data Transformation

In [ ]:
df.isna().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [ ]:
df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
...,...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64,0
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77,0
9997,709,France,Female,36,7,0.00,1,0,1,42085.58,1
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52,1
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78,0

In [ ]:
df.drop(columns = ['Exited'])

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10
...,...,...,...,...,...,...,...,...,...,...
9995,771,France,Male,39,5,0.00,2,1,0,96270.64
9996,516,France,Male,35,10,57369.61,1,1,1,101699.77
9997,709,France,Female,36,7,0.00,1,0,1,42085.58
9998,772,Germany,Male,42,3,75075.31,2,1,0,92888.52
9999,792,France,Female,28,4,130142.79,1,1,0,38190.78

In [ ]:
pd.get_dummies(data = df, columns = ['Geography','Gender'])

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,True,False,False,True,False
1,608,41,1,83807.86,1,0,1,112542.58,0,False,False,True,True,False
2,502,42,8,159660.80,3,1,0,113931.57,1,True,False,False,True,False
3,699,39,1,0.00,2,0,0,93826.63,0,True,False,False,True,False
4,850,43,2,125510.82,1,1,1,79084.10,0,False,False,True,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,True,False,False,False,True
9996,516,35,10,57369.61,1,1,1,101699.77,0,True,False,False,False,True
9997,709,36,7,0.00,1,0,1,42085.58,1,True,False,False,True,False
9998,772,42,3,75075.31,2,1,0,92888.52,1,False,True,False,False,True
9999,792,28,4,130142.79,1,1,0,38190.78,0,True,False,False,True,False

In [ ]:
df = pd.get_dummies(data=df, columns=['Geography','Gender'],dtype = int)
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,1,0,0,1,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,0,1,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,1,0,0,1,0
3,699,39,1,0.00,2,0,0,93826.63,0,1,0,0,1,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,1,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,1,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,1,0,0,1,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,0,1,0,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,1,0,0,1,0

# Model Building

In [ ]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,1,0,0,1,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,0,1,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,1,0,0,1,0
3,699,39,1,0.00,2,0,0,93826.63,0,1,0,0,1,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,1,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,1,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,1,0,0,1,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,0,1,0,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,1,0,0,1,0

In [ ]:
df.drop(columns = ['Exited'])

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,1,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,1,0
3,699,39,1,0.00,2,0,0,93826.63,1,0,0,1,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,1,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,1,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,0,0,1,0
9998,772,42,3,75075.31,2,1,0,92888.52,0,1,0,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,1,0,0,1,0

In [ ]:
df

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,1,0,0,1,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,0,1,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,1,0,0,1,0
3,699,39,1,0.00,2,0,0,93826.63,0,1,0,0,1,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,0,1,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,0,1,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,1,0,0,1,0
9998,772,42,3,75075.31,2,1,0,92888.52,1,0,1,0,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,0,1,0,0,1,0

In [ ]:
sc = StandardScaler()
x = df.drop(columns=['Exited'])
y = df['Exited']

In [ ]:
x

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,0,0,1,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,1,1,0
2,502,42,8,159660.80,3,1,0,113931.57,1,0,0,1,0
3,699,39,1,0.00,2,0,0,93826.63,1,0,0,1,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,39,5,0.00,2,1,0,96270.64,1,0,0,0,1
9996,516,35,10,57369.61,1,1,1,101699.77,1,0,0,0,1
9997,709,36,7,0.00,1,0,1,42085.58,1,0,0,1,0
9998,772,42,3,75075.31,2,1,0,92888.52,0,1,0,0,1
9999,792,28,4,130142.79,1,1,0,38190.78,1,0,0,1,0

In [ ]:
x = sc.fit_transform(x)
x

array([[-0.32622142,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.44003595,  0.19816383, -1.38753759, ...,  1.74273971,
         1.09598752, -1.09598752],
       [-1.53679418,  0.29351742,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.60498839, -0.27860412,  0.68712986, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.25683526,  0.29351742, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 1.46377078, -1.04143285, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752]])

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.20, random_state=1)

In [ ]:
xtrain

array([[-0.23310044, -0.94607926, -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [-0.25379399, -0.94607926, -0.35020386, ..., -0.57380915,
         1.09598752, -1.09598752],
       [-0.39864885,  0.77028538,  0.34135195, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [ 0.22215769,  0.5795782 ,  1.37868567, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 0.12903671,  0.00745665,  1.03290776, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 1.16371428,  0.29351742,  0.34135195, ..., -0.57380915,
        -0.91241915,  0.91241915]])

In [ ]:
#Initialize model
ann = Sequential()

#Add hidden layer
ann.add(Dense(units=10,activation='relu'))

#Add output layer
ann.add(Dense(units=1, activation='sigmoid'))

#Establish the connection between the layers
ann.compile(optimizer = 'adadelta',loss='binary_crossentropy',metrics='accuracy')

#Fit the data
ann.fit(xtrain,ytrain, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7711 - accuracy: 0.4900
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7697 - accuracy: 0.4910
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7683 - accuracy: 0.4922
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7669 - accuracy: 0.4938
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7654 - accuracy: 0.4958
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7639 - accuracy: 0.4978
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7624 - accuracy: 0.4989
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7609 - accuracy: 0.5008
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.7594 - accuracy: 0.5015
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7579 - accuracy: 0.5026
Epoch 11/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7563 - accuracy: 0.5035
Epoch 12/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7548 - accuracy: 0.5048
Epoch 13/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7533 - accuracy: 0.5063
Epoch 14/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7518 - accuracy: 0.5082
Epoch 15/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7503 - accuracy: 0.5092
Epoch 16/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7488 - accuracy: 0.5098
Epoch 17/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7473 - accuracy: 0.5111
Epoch 18/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7458 - accuracy: 0.5125
Epoch 19/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7443 - accuracy: 0.5136
Epoch 20/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7428 - accuracy: 0.5146
Epoch 21/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7413 - accuracy: 0.5163
Epoch 22/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7398 - accuracy: 0.5181
Epoch 23/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7383 - accuracy: 0.5189
Epoch 24/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7368 - accuracy: 0.5204
Epoch 25/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7354 - accuracy: 0.5209
Epoch 26/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7339 - accuracy: 0.5215
Epoch 27/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7324 - accuracy: 0.5234
Epoch 28/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7310 - accuracy: 0.5235
Epoch 29/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7295 - accuracy: 0.5255
Epoch 30/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7281 - accuracy: 0.5270
Epoch 31/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7267 - accuracy: 0.5279
Epoch 32/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7252 - accuracy: 0.5294
Epoch 33/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7238 - accuracy: 0.5306
Epoch 34/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7224 - accuracy: 0.5326
Epoch 35/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7210 - accuracy: 0.5347
Epoch 36/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7196 - accuracy: 0.5364
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 0.7183 - accuracy: 0.5379
Epoch 38/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7169 - accuracy: 0.5390
Epoch 39/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7155 - accuracy: 0.5404
Epoch 40/100
250/250 [==============================] - 1s 3ms/step - loss: 0.7141 - accuracy: 0.5414
Epoch 41/100
250/250 [==============================] - 1s 3ms/step - loss: 0.7128 - accuracy: 0.5433
Epoch 42/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7114 - accuracy: 0.5446
Epoch 43/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7101 - accuracy: 0.5455
Epoch 44/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7087 - accuracy: 0.5464
Epoch 45/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7074 - accuracy: 0.5481
Epoch 46/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7061 - accuracy: 0.5505
Epoch 47/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7048 - accuracy: 0.5510
Epoch 48/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7035 - accuracy: 0.5524
Epoch 49/100
250/250 [==============================] - 0s 1ms/step - loss: 0.7022 - accuracy: 0.5534
Epoch 50/100
250/250 [==============================] - 0s 2ms/step - loss: 0.7009 - accuracy: 0.5539
Epoch 51/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6996 - accuracy: 0.5555
Epoch 52/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6983 - accuracy: 0.5569
Epoch 53/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6970 - accuracy: 0.5586
Epoch 54/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6957 - accuracy: 0.5608
Epoch 55/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6945 - accuracy: 0.5621
Epoch 56/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6932 - accuracy: 0.5631
Epoch 57/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6919 - accuracy: 0.5646
Epoch 58/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6907 - accuracy: 0.5660
Epoch 59/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6894 - accuracy: 0.5670
Epoch 60/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6882 - accuracy: 0.5680
Epoch 61/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6870 - accuracy: 0.5696
Epoch 62/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6857 - accuracy: 0.5710
Epoch 63/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6845 - accuracy: 0.5725
Epoch 64/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6833 - accuracy: 0.5731
Epoch 65/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6821 - accuracy: 0.5748
Epoch 66/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6809 - accuracy: 0.5761
Epoch 67/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6798 - accuracy: 0.5770
Epoch 68/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6786 - accuracy: 0.5784
Epoch 69/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6774 - accuracy: 0.5801
Epoch 70/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6763 - accuracy: 0.5815
Epoch 71/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6751 - accuracy: 0.5826
Epoch 72/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6740 - accuracy: 0.5830
Epoch 73/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6728 - accuracy: 0.5840
Epoch 74/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6717 - accuracy: 0.5857
Epoch 75/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6706 - accuracy: 0.5869
Epoch 76/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6695 - accuracy: 0.5886
Epoch 77/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6683 - accuracy: 0.5899
Epoch 78/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6672 - accuracy: 0.5911
Epoch 79/100
250/250 [==============================] - 0s 1ms/step - loss: 0.6661 - accuracy: 0.5926
Epoch 80/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6650 - accuracy: 0.5945
Epoch 81/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6639 - accuracy: 0.5959
Epoch 82/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6628 - accuracy: 0.5976
Epoch 83/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6617 - accuracy: 0.5989
Epoch 84/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6606 - accuracy: 0.6001
Epoch 85/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6596 - accuracy: 0.6012
Epoch 86/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6585 - accuracy: 0.6030
Epoch 87/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6574 - accuracy: 0.6034
Epoch 88/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6564 - accuracy: 0.6049
Epoch 89/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6553 - accuracy: 0.6064
Epoch 90/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6543 - accuracy: 0.6074
Epoch 91/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6532 - accuracy: 0.6087
Epoch 92/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6522 - accuracy: 0.6100
Epoch 93/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6511 - accuracy: 0.6110
Epoch 94/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6501 - accuracy: 0.6120
Epoch 95/100
250/250 [==============================] - 0s 2ms/step - loss: 0.6491 - accuracy: 0.6131
Epoch 96/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6481 - accuracy: 0.6155
Epoch 97/100
250/250 [==============================] - 1s 4ms/step - loss: 0.6471 - accuracy: 0.6168
Epoch 98/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6461 - accuracy: 0.6180
Epoch 99/100
250/250 [==============================] - 1s 3ms/step - loss: 0.6451 - accuracy: 0.6190
Epoch 100/100
250/250 [==============================] - 1s 2ms/step - loss: 0.6441 - accuracy: 0.6205

In [ ]:
xtest

array([[-1.04014895,  0.77028538, -1.04175968, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [ 0.3049319 , -0.4693113 , -0.69598177, ..., -0.57380915,
        -0.91241915,  0.91241915],
       [-1.23673768,  0.29351742, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       ...,
       [-0.86425376, -0.4693113 ,  1.72446358, ...,  1.74273971,
        -0.91241915,  0.91241915],
       [-0.30552787, -0.85072567, -1.04175968, ..., -0.57380915,
         1.09598752, -1.09598752],
       [ 0.0462625 ,  1.24705333,  1.37868567, ..., -0.57380915,
        -0.91241915,  0.91241915]])

In [ ]:
ypred = ann.predict(xtest)
ypred

63/63 [==============================] - 0s 1ms/step

array([[0.38973948],
       [0.5647748 ],
       [0.57638824],
       ...,
       [0.27929375],
       [0.34079316],
       [0.60849184]], dtype=float32)

In [ ]:
ytest

9953    0
3850    0
4962    0
3886    0
5437    0
       ..
3919    0
162     0
7903    0
2242    0
2745    0
Name: Exited, Length: 2000, dtype: int64

In [ ]:
print(classification_report(ytest,ypred))     #Because above ytest in all values are 0.  here want to 0, 1 included.

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [ ]:
ypred > 0.5

array([[False],
       [ True],
       [ True],
       ...,
       [False],
       [False],
       [ True]])

In [ ]:
ypred = ypred > 0.5
ypred

array([[False],
       [ True],
       [ True],
       ...,
       [False],
       [False],
       [ True]])

In [ ]:
ytest

9953    0
3850    0
4962    0
3886    0
5437    0
       ..
3919    0
162     0
7903    0
2242    0
2745    0
Name: Exited, Length: 2000, dtype: int64

In [ ]:
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.88      0.64      0.74      1585
           1       0.33      0.67      0.44       415

    accuracy                           0.64      2000
   macro avg       0.60      0.66      0.59      2000
weighted avg       0.77      0.64      0.68      2000

# Hyperparameter Tuning

In [ ]:
!pip install -U keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.7-py3-none-any.whl (129 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 kB 3.2 MB/s eta 0:00:00
Requirement already satisfied: keras in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (2.15.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (24.1)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from keras-tuner) (2.31.0)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->keras-tuner) (2024.7.4)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.7 kt-legacy-1.0.5

# **Tuning the ANN Model**
- Selecting the best optimizer

In [ ]:
import keras_tuner as kt

In [ ]:
def optimizer_selection(hp):
    #initialize the model
    model = Sequential()
    #Add hidden layer
    model.add(Dense(units=10, activation='relu'))
    #Add output layer
    model.add(Dense(units=1, activation='sigmoid'))
    #Optimizer selection
    optim = hp.Choice('optimizer', values = ['sgd','adam','rmsprop'])
    model.compile(optimizer=optim, loss = 'binary_crossentropy', metrics = 'accuracy')
    return model

In [ ]:
tuner = kt.RandomSearch(
    optimizer_selection,
    objective='val_accuracy',
    max_trials=3
)

In [ ]:
tuner.search(xtrain,ytrain, epochs = 3, validation_data = (xtest,ytest))

Trial 3 Complete [00h 00m 04s]
val_accuracy: 0.8209999799728394

Best val_accuracy So Far: 0.8209999799728394
Total elapsed time: 00h 00m 10s

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

In [ ]:
model = tuner.get_best_models(num_models=1)[0]
model.fit(xtrain,ytrain, epochs = 100, validation_data = (xtest,ytest))

Epoch 1/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4087 - accuracy: 0.8254 - val_loss: 0.4012 - val_accuracy: 0.8260
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3960 - accuracy: 0.8359 - val_loss: 0.3899 - val_accuracy: 0.8330
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3856 - accuracy: 0.8434 - val_loss: 0.3807 - val_accuracy: 0.8445
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3774 - accuracy: 0.8460 - val_loss: 0.3735 - val_accuracy: 0.8495
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3706 - accuracy: 0.8512 - val_loss: 0.3681 - val_accuracy: 0.8520
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3653 - accuracy: 0.8535 - val_loss: 0.3628 - val_accuracy: 0.8545
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3607 - accuracy: 0.8544 - val_loss: 0.3590 - val_accuracy: 0.8570
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3579 - accuracy: 0.8541 - val_loss: 0.3551 - val_accuracy: 0.8540
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3553 - accuracy: 0.8560 - val_loss: 0.3524 - val_accuracy: 0.8565
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3533 - accuracy: 0.8562 - val_loss: 0.3517 - val_accuracy: 0.8555
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3519 - accuracy: 0.8562 - val_loss: 0.3500 - val_accuracy: 0.8575
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3507 - accuracy: 0.8574 - val_loss: 0.3488 - val_accuracy: 0.8585
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3495 - accuracy: 0.8576 - val_loss: 0.3476 - val_accuracy: 0.8570
Epoch 14/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3489 - accuracy: 0.8570 - val_loss: 0.3463 - val_accuracy: 0.8580
Epoch 15/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3482 - accuracy: 0.8566 - val_loss: 0.3459 - val_accuracy: 0.8590
Epoch 16/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3476 - accuracy: 0.8590 - val_loss: 0.3465 - val_accuracy: 0.8575
Epoch 17/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3472 - accuracy: 0.8581 - val_loss: 0.3445 - val_accuracy: 0.8600
Epoch 18/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3466 - accuracy: 0.8574 - val_loss: 0.3448 - val_accuracy: 0.8595
Epoch 19/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3462 - accuracy: 0.8581 - val_loss: 0.3454 - val_accuracy: 0.8595
Epoch 20/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3459 - accuracy: 0.8586 - val_loss: 0.3441 - val_accuracy: 0.8610
Epoch 21/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3455 - accuracy: 0.8585 - val_loss: 0.3441 - val_accuracy: 0.8600
Epoch 22/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3455 - accuracy: 0.8585 - val_loss: 0.3431 - val_accuracy: 0.8615
Epoch 23/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3452 - accuracy: 0.8580 - val_loss: 0.3429 - val_accuracy: 0.8610
Epoch 24/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3451 - accuracy: 0.8583 - val_loss: 0.3429 - val_accuracy: 0.8605
Epoch 25/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3446 - accuracy: 0.8589 - val_loss: 0.3425 - val_accuracy: 0.8585
Epoch 26/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3445 - accuracy: 0.8599 - val_loss: 0.3431 - val_accuracy: 0.8640
Epoch 27/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3441 - accuracy: 0.8590 - val_loss: 0.3429 - val_accuracy: 0.8635
Epoch 28/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3442 - accuracy: 0.8584 - val_loss: 0.3418 - val_accuracy: 0.8630
Epoch 29/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3440 - accuracy: 0.8595 - val_loss: 0.3417 - val_accuracy: 0.8660
Epoch 30/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3440 - accuracy: 0.8596 - val_loss: 0.3419 - val_accuracy: 0.8640
Epoch 31/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3437 - accuracy: 0.8589 - val_loss: 0.3411 - val_accuracy: 0.8625
Epoch 32/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3437 - accuracy: 0.8599 - val_loss: 0.3413 - val_accuracy: 0.8620
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3435 - accuracy: 0.8590 - val_loss: 0.3407 - val_accuracy: 0.8620
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3435 - accuracy: 0.8589 - val_loss: 0.3396 - val_accuracy: 0.8615
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3433 - accuracy: 0.8589 - val_loss: 0.3397 - val_accuracy: 0.8615
Epoch 36/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3432 - accuracy: 0.8599 - val_loss: 0.3397 - val_accuracy: 0.8625
Epoch 37/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3434 - accuracy: 0.8594 - val_loss: 0.3401 - val_accuracy: 0.8625
Epoch 38/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3432 - accuracy: 0.8596 - val_loss: 0.3398 - val_accuracy: 0.8615
Epoch 39/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3430 - accuracy: 0.8599 - val_loss: 0.3393 - val_accuracy: 0.8620
Epoch 40/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3429 - accuracy: 0.8600 - val_loss: 0.3390 - val_accuracy: 0.8605
Epoch 41/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3426 - accuracy: 0.8591 - val_loss: 0.3394 - val_accuracy: 0.8620
Epoch 42/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3427 - accuracy: 0.8597 - val_loss: 0.3390 - val_accuracy: 0.8635
Epoch 43/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3427 - accuracy: 0.8605 - val_loss: 0.3389 - val_accuracy: 0.8625
Epoch 44/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3423 - accuracy: 0.8590 - val_loss: 0.3389 - val_accuracy: 0.8620
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3428 - accuracy: 0.8605 - val_loss: 0.3388 - val_accuracy: 0.8620
Epoch 46/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3425 - accuracy: 0.8597 - val_loss: 0.3392 - val_accuracy: 0.8635
Epoch 47/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3426 - accuracy: 0.8595 - val_loss: 0.3396 - val_accuracy: 0.8650
Epoch 48/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3425 - accuracy: 0.8589 - val_loss: 0.3383 - val_accuracy: 0.8630
Epoch 49/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3424 - accuracy: 0.8597 - val_loss: 0.3388 - val_accuracy: 0.8630
Epoch 50/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3421 - accuracy: 0.8591 - val_loss: 0.3394 - val_accuracy: 0.8645
Epoch 51/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3419 - accuracy: 0.8585 - val_loss: 0.3385 - val_accuracy: 0.8640
Epoch 52/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3423 - accuracy: 0.8590 - val_loss: 0.3380 - val_accuracy: 0.8615
Epoch 53/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3423 - accuracy: 0.8611 - val_loss: 0.3383 - val_accuracy: 0.8645
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3417 - accuracy: 0.8601 - val_loss: 0.3388 - val_accuracy: 0.8620
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3423 - accuracy: 0.8591 - val_loss: 0.3390 - val_accuracy: 0.8620
Epoch 56/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3418 - accuracy: 0.8599 - val_loss: 0.3389 - val_accuracy: 0.8620
Epoch 57/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3419 - accuracy: 0.8586 - val_loss: 0.3381 - val_accuracy: 0.8620
Epoch 58/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3418 - accuracy: 0.8600 - val_loss: 0.3380 - val_accuracy: 0.8635
Epoch 59/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3416 - accuracy: 0.8615 - val_loss: 0.3383 - val_accuracy: 0.8605
Epoch 60/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3416 - accuracy: 0.8597 - val_loss: 0.3388 - val_accuracy: 0.8665
Epoch 61/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3414 - accuracy: 0.8611 - val_loss: 0.3382 - val_accuracy: 0.8635
Epoch 62/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3414 - accuracy: 0.8600 - val_loss: 0.3394 - val_accuracy: 0.8615
Epoch 63/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3415 - accuracy: 0.8601 - val_loss: 0.3382 - val_accuracy: 0.8625
Epoch 64/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3414 - accuracy: 0.8612 - val_loss: 0.3379 - val_accuracy: 0.8615
Epoch 65/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3415 - accuracy: 0.8604 - val_loss: 0.3383 - val_accuracy: 0.8600
Epoch 66/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3410 - accuracy: 0.8600 - val_loss: 0.3389 - val_accuracy: 0.8655
Epoch 67/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3412 - accuracy: 0.8609 - val_loss: 0.3378 - val_accuracy: 0.8620
Epoch 68/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3409 - accuracy: 0.8611 - val_loss: 0.3388 - val_accuracy: 0.8595
Epoch 69/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3412 - accuracy: 0.8605 - val_loss: 0.3386 - val_accuracy: 0.8610
Epoch 70/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3409 - accuracy: 0.8612 - val_loss: 0.3389 - val_accuracy: 0.8610
Epoch 71/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3408 - accuracy: 0.8610 - val_loss: 0.3391 - val_accuracy: 0.8630
Epoch 72/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3405 - accuracy: 0.8606 - val_loss: 0.3385 - val_accuracy: 0.8630
Epoch 73/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3407 - accuracy: 0.8608 - val_loss: 0.3376 - val_accuracy: 0.8610
Epoch 74/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3407 - accuracy: 0.8594 - val_loss: 0.3389 - val_accuracy: 0.8630
Epoch 75/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3409 - accuracy: 0.8614 - val_loss: 0.3392 - val_accuracy: 0.8600
Epoch 76/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3408 - accuracy: 0.8601 - val_loss: 0.3383 - val_accuracy: 0.8595
Epoch 77/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3408 - accuracy: 0.8596 - val_loss: 0.3385 - val_accuracy: 0.8605
Epoch 78/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3408 - accuracy: 0.8604 - val_loss: 0.3376 - val_accuracy: 0.8615
Epoch 79/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3406 - accuracy: 0.8615 - val_loss: 0.3375 - val_accuracy: 0.8605
Epoch 80/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3400 - accuracy: 0.8602 - val_loss: 0.3389 - val_accuracy: 0.8655
Epoch 81/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3406 - accuracy: 0.8616 - val_loss: 0.3395 - val_accuracy: 0.8625
Epoch 82/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3403 - accuracy: 0.8612 - val_loss: 0.3390 - val_accuracy: 0.8625
Epoch 83/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3403 - accuracy: 0.8599 - val_loss: 0.3380 - val_accuracy: 0.8630
Epoch 84/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3404 - accuracy: 0.8605 - val_loss: 0.3374 - val_accuracy: 0.8635
Epoch 85/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3402 - accuracy: 0.8609 - val_loss: 0.3400 - val_accuracy: 0.8630
Epoch 86/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3404 - accuracy: 0.8606 - val_loss: 0.3390 - val_accuracy: 0.8630
Epoch 87/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3401 - accuracy: 0.8610 - val_loss: 0.3373 - val_accuracy: 0.8620
Epoch 88/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3398 - accuracy: 0.8595 - val_loss: 0.3382 - val_accuracy: 0.8620
Epoch 89/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3397 - accuracy: 0.8612 - val_loss: 0.3373 - val_accuracy: 0.8625
Epoch 90/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3400 - accuracy: 0.8616 - val_loss: 0.3369 - val_accuracy: 0.8610
Epoch 91/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3396 - accuracy: 0.8621 - val_loss: 0.3383 - val_accuracy: 0.8615
Epoch 92/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3403 - accuracy: 0.8611 - val_loss: 0.3384 - val_accuracy: 0.8620
Epoch 93/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3397 - accuracy: 0.8624 - val_loss: 0.3381 - val_accuracy: 0.8605
Epoch 94/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3399 - accuracy: 0.8616 - val_loss: 0.3372 - val_accuracy: 0.8595
Epoch 95/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3397 - accuracy: 0.8610 - val_loss: 0.3384 - val_accuracy: 0.8635
Epoch 96/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3390 - accuracy: 0.8605 - val_loss: 0.3365 - val_accuracy: 0.8625
Epoch 97/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3397 - accuracy: 0.8609 - val_loss: 0.3371 - val_accuracy: 0.8620
Epoch 98/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3399 - accuracy: 0.8609 - val_loss: 0.3373 - val_accuracy: 0.8610
Epoch 99/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3393 - accuracy: 0.8610 - val_loss: 0.3383 - val_accuracy: 0.8630
Epoch 100/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3396 - accuracy: 0.8610 - val_loss: 0.3377 - val_accuracy: 0.8590

In [ ]:
model.evaluate(xtrain,ytrain)

250/250 [==============================] - 1s 2ms/step - loss: 0.3378 - accuracy: 0.8640

[0.3377930819988251, 0.8640000224113464]

# Regression

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/Shrikrishna-jadhavar/Data-Science-Material/main/Dataset/Regression.csv')
df

          price     feature1     feature2
0    461.527929   999.787558   999.766096
1    548.130012   998.861615  1001.042403
2    410.297162  1000.070267   998.844015
3    540.382220   999.952251  1000.440940
4    546.024553  1000.446011  1000.338531
..          ...          ...          ...
995  476.526078  1000.018988   999.672732
996  457.313186   998.855379  1000.020026
997  456.720993  1001.451646   998.847605
998  403.315576  1000.771023   998.562851
999  599.367094   999.232244  1001.451407

[1000 rows x 3 columns]

In [ ]:
x = df.iloc[:,1:]
y = df['price']

In [ ]:
x = sc.fit_transform(x)
x

array([[-0.23277509, -0.22551031],
       [-1.18389307,  1.12100979],
       [ 0.05762098, -1.19831827],
       ...,
       [ 1.47655818, -1.19452982],
       [ 0.77742978, -1.49494959],
       [-0.80318737,  1.55251428]])

In [ ]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2, random_state=1)

In [ ]:
ann = Sequential()

ann.add(Dense(units=30, activation='relu'))
ann.add(Dense(units=20, activation='relu'))

ann.add(Dense(units=1))

ann.compile(optimizer='adam',loss = 'mse')

ann.fit(xtrain,ytrain, epochs = 100, validation_data = (xtest,ytest))

Epoch 1/100
25/25 [==============================] - 1s 9ms/step - loss: 255906.6250 - val_loss: 262624.1250
Epoch 2/100
25/25 [==============================] - 0s 3ms/step - loss: 255354.2188 - val_loss: 261930.6250
Epoch 3/100
25/25 [==============================] - 0s 3ms/step - loss: 254471.7188 - val_loss: 260832.8750
Epoch 4/100
25/25 [==============================] - 0s 3ms/step - loss: 253117.0938 - val_loss: 259196.7188
Epoch 5/100
25/25 [==============================] - 0s 3ms/step - loss: 251137.5938 - val_loss: 256810.0938
Epoch 6/100
25/25 [==============================] - 0s 4ms/step - loss: 248284.5469 - val_loss: 253429.7188
Epoch 7/100
25/25 [==============================] - 0s 4ms/step - loss: 244321.1875 - val_loss: 248774.7031
Epoch 8/100
25/25 [==============================] - 0s 6ms/step - loss: 238998.2969 - val_loss: 242625.7031
Epoch 9/100
25/25 [==============================] - 0s 4ms/step - loss: 232102.0781 - val_loss: 234801.0000
Epoch 10/100
25/25 [==============================] - 0s 5ms/step - loss: 223448.1250 - val_loss: 225188.7188
Epoch 11/100
25/25 [==============================] - 0s 5ms/step - loss: 213078.2344 - val_loss: 213630.7812
Epoch 12/100
25/25 [==============================] - 0s 4ms/step - loss: 200843.2969 - val_loss: 200475.5469
Epoch 13/100
25/25 [==============================] - 0s 4ms/step - loss: 186983.4219 - val_loss: 185616.9375
Epoch 14/100
25/25 [==============================] - 0s 4ms/step - loss: 171692.4219 - val_loss: 169101.9062
Epoch 15/100
25/25 [==============================] - 0s 5ms/step - loss: 154816.2344 - val_loss: 151926.2969
Epoch 16/100
25/25 [==============================] - 0s 3ms/step - loss: 137291.2812 - val_loss: 133803.5156
Epoch 17/100
25/25 [==============================] - 0s 4ms/step - loss: 119362.9688 - val_loss: 115407.2734
Epoch 18/100
25/25 [==============================] - 0s 4ms/step - loss: 101543.4609 - val_loss: 97409.4766
Epoch 19/100
25/25 [==============================] - 0s 5ms/step - loss: 84387.4297 - val_loss: 80566.4922
Epoch 20/100
25/25 [==============================] - 0s 4ms/step - loss: 68602.4219 - val_loss: 65074.3242
Epoch 21/100
25/25 [==============================] - 0s 4ms/step - loss: 54452.1250 - val_loss: 51524.9492
Epoch 22/100
25/25 [==============================] - 0s 4ms/step - loss: 42362.1250 - val_loss: 39965.8906
Epoch 23/100
25/25 [==============================] - 0s 4ms/step - loss: 32367.1270 - val_loss: 30628.9902
Epoch 24/100
25/25 [==============================] - 0s 3ms/step - loss: 24479.1895 - val_loss: 23411.4316
Epoch 25/100
25/25 [==============================] - 0s 3ms/step - loss: 18600.2617 - val_loss: 17949.7051
Epoch 26/100
25/25 [==============================] - 0s 3ms/step - loss: 14325.9648 - val_loss: 14090.6963
Epoch 27/100
25/25 [==============================] - 0s 3ms/step - loss: 11385.5703 - val_loss: 11439.6611
Epoch 28/100
25/25 [==============================] - 0s 3ms/step - loss: 9431.2520 - val_loss: 9647.5508
Epoch 29/100
25/25 [==============================] - 0s 4ms/step - loss: 8146.5513 - val_loss: 8414.6729
Epoch 30/100
25/25 [==============================] - 0s 4ms/step - loss: 7285.8936 - val_loss: 7599.5879
Epoch 31/100
25/25 [==============================] - 0s 4ms/step - loss: 6721.5498 - val_loss: 6994.2295
Epoch 32/100
25/25 [==============================] - 0s 3ms/step - loss: 6308.0142 - val_loss: 6546.8018
Epoch 33/100
25/25 [==============================] - 0s 3ms/step - loss: 5978.8218 - val_loss: 6196.3877
Epoch 34/100
25/25 [==============================] - 0s 3ms/step - loss: 5694.9844 - val_loss: 5889.0024
Epoch 35/100
25/25 [==============================] - 0s 3ms/step - loss: 5447.8311 - val_loss: 5612.1968
Epoch 36/100
25/25 [==============================] - 0s 3ms/step - loss: 5215.1465 - val_loss: 5348.8311
Epoch 37/100
25/25 [==============================] - 0s 3ms/step - loss: 4987.5234 - val_loss: 5104.0640
Epoch 38/100
25/25 [==============================] - 0s 3ms/step - loss: 4766.8765 - val_loss: 4867.3301
Epoch 39/100
25/25 [==============================] - 0s 4ms/step - loss: 4554.4863 - val_loss: 4653.4385
Epoch 40/100
25/25 [==============================] - 0s 4ms/step - loss: 4345.7207 - val_loss: 4425.2583
Epoch 41/100
25/25 [==============================] - 0s 4ms/step - loss: 4142.6304 - val_loss: 4215.9971
Epoch 42/100
25/25 [==============================] - 0s 4ms/step - loss: 3947.0447 - val_loss: 4000.6450
Epoch 43/100
25/25 [==============================] - 0s 4ms/step - loss: 3761.7134 - val_loss: 3804.4478
Epoch 44/100
25/25 [==============================] - 0s 3ms/step - loss: 3569.5283 - val_loss: 3619.4297
Epoch 45/100
25/25 [==============================] - 0s 3ms/step - loss: 3393.9163 - val_loss: 3436.4841
Epoch 46/100
25/25 [==============================] - 0s 3ms/step - loss: 3223.8936 - val_loss: 3261.4795
Epoch 47/100
25/25 [==============================] - 0s 3ms/step - loss: 3060.0166 - val_loss: 3084.4194
Epoch 48/100
25/25 [==============================] - 0s 4ms/step - loss: 2901.2893 - val_loss: 2924.8337
Epoch 49/100
25/25 [==============================] - 0s 4ms/step - loss: 2754.3899 - val_loss: 2775.8708
Epoch 50/100
25/25 [==============================] - 0s 5ms/step - loss: 2608.0571 - val_loss: 2632.0625
Epoch 51/100
25/25 [==============================] - 0s 5ms/step - loss: 2471.5366 - val_loss: 2492.4187
Epoch 52/100
25/25 [==============================] - 0s 4ms/step - loss: 2347.9983 - val_loss: 2358.9321
Epoch 53/100
25/25 [==============================] - 0s 3ms/step - loss: 2218.0410 - val_loss: 2237.7776
Epoch 54/100
25/25 [==============================] - 0s 3ms/step - loss: 2101.1626 - val_loss: 2122.6860
Epoch 55/100
25/25 [==============================] - 0s 4ms/step - loss: 1989.9297 - val_loss: 2007.0283
Epoch 56/100
25/25 [==============================] - 0s 4ms/step - loss: 1885.0576 - val_loss: 1894.8364
Epoch 57/100
25/25 [==============================] - 0s 4ms/step - loss: 1785.8353 - val_loss: 1801.6859
Epoch 58/100
25/25 [==============================] - 0s 4ms/step - loss: 1686.9016 - val_loss: 1709.0062
Epoch 59/100
25/25 [==============================] - 0s 4ms/step - loss: 1602.1027 - val_loss: 1615.2322
Epoch 60/100
25/25 [==============================] - 0s 6ms/step - loss: 1513.0121 - val_loss: 1532.2316
Epoch 61/100
25/25 [==============================] - 0s 5ms/step - loss: 1432.9167 - val_loss: 1460.2802
Epoch 62/100
25/25 [==============================] - 0s 4ms/step - loss: 1357.6194 - val_loss: 1383.2333
Epoch 63/100
25/25 [==============================] - 0s 4ms/step - loss: 1283.1993 - val_loss: 1314.6279
Epoch 64/100
25/25 [==============================] - 0s 4ms/step - loss: 1217.4988 - val_loss: 1249.0516
Epoch 65/100
25/25 [==============================] - 0s 4ms/step - loss: 1152.2277 - val_loss: 1189.9358
Epoch 66/100
25/25 [==============================] - 0s 3ms/step - loss: 1093.7145 - val_loss: 1128.7827
Epoch 67/100
25/25 [==============================] - 0s 3ms/step - loss: 1035.0396 - val_loss: 1074.0264
Epoch 68/100
25/25 [==============================] - 0s 3ms/step - loss: 983.7709 - val_loss: 1025.5037
Epoch 69/100
25/25 [==============================] - 0s 4ms/step - loss: 933.7302 - val_loss: 974.4476
Epoch 70/100
25/25 [==============================] - 0s 4ms/step - loss: 885.7643 - val_loss: 929.5184
Epoch 71/100
25/25 [==============================] - 0s 3ms/step - loss: 840.9730 - val_loss: 885.1717
Epoch 72/100
25/25 [==============================] - 0s 3ms/step - loss: 799.7911 - val_loss: 844.4386
Epoch 73/100
25/25 [==============================] - 0s 3ms/step - loss: 760.1992 - val_loss: 808.8278
Epoch 74/100
25/25 [==============================] - 0s 3ms/step - loss: 724.3674 - val_loss: 772.2379
Epoch 75/100
25/25 [==============================] - 0s 4ms/step - loss: 689.2240 - val_loss: 737.5316
Epoch 76/100
25/25 [==============================] - 0s 3ms/step - loss: 656.6314 - val_loss: 706.9791
Epoch 77/100
25/25 [==============================] - 0s 4ms/step - loss: 626.1755 - val_loss: 678.3445
Epoch 78/100
25/25 [==============================] - 0s 3ms/step - loss: 597.9317 - val_loss: 651.7209
Epoch 79/100
25/25 [==============================] - 0s 4ms/step - loss: 570.9214 - val_loss: 626.2597
Epoch 80/100
25/25 [==============================] - 0s 4ms/step - loss: 545.4830 - val_loss: 598.7762
Epoch 81/100
25/25 [==============================] - 0s 6ms/step - loss: 523.2721 - val_loss: 574.1401
Epoch 82/100
25/25 [==============================] - 0s 5ms/step - loss: 499.2377 - val_loss: 553.8450
Epoch 83/100
25/25 [==============================] - 0s 5ms/step - loss: 477.8711 - val_loss: 535.4174
Epoch 84/100
25/25 [==============================] - 0s 5ms/step - loss: 458.2919 - val_loss: 515.1967
Epoch 85/100
25/25 [==============================] - 0s 4ms/step - loss: 439.3068 - val_loss: 494.9835
Epoch 86/100
25/25 [==============================] - 0s 5ms/step - loss: 422.1404 - val_loss: 478.8583
Epoch 87/100
25/25 [==============================] - 0s 5ms/step - loss: 404.9867 - val_loss: 458.7273
Epoch 88/100
25/25 [==============================] - 0s 5ms/step - loss: 388.6664 - val_loss: 444.1667
Epoch 89/100
25/25 [==============================] - 0s 6ms/step - loss: 374.0286 - val_loss: 429.4568
Epoch 90/100
25/25 [==============================] - 0s 5ms/step - loss: 360.8238 - val_loss: 415.7837
Epoch 91/100
25/25 [==============================] - 0s 5ms/step - loss: 346.7336 - val_loss: 400.8130
Epoch 92/100
25/25 [==============================] - 0s 5ms/step - loss: 334.2606 - val_loss: 388.9057
Epoch 93/100
25/25 [==============================] - 0s 5ms/step - loss: 323.2925 - val_loss: 376.2221
Epoch 94/100
25/25 [==============================] - 0s 8ms/step - loss: 310.9614 - val_loss: 364.0431
Epoch 95/100
25/25 [==============================] - 0s 10ms/step - loss: 300.0736 - val_loss: 353.7835
Epoch 96/100
25/25 [==============================] - 0s 8ms/step - loss: 289.6354 - val_loss: 343.0641
Epoch 97/100
25/25 [==============================] - 0s 7ms/step - loss: 279.4447 - val_loss: 332.4936
Epoch 98/100
25/25 [==============================] - 0s 7ms/step - loss: 270.3701 - val_loss: 322.3277
Epoch 99/100
25/25 [==============================] - 0s 6ms/step - loss: 260.7623 - val_loss: 313.8450
Epoch 100/100
25/25 [==============================] - 0s 8ms/step - loss: 251.9729 - val_loss: 304.4425

In [ ]:
yp = ann.predict(xtest)
yp

7/7 [==============================] - 0s 2ms/step

array([[479.43246],
       [527.5268 ],
       [497.9085 ],
       [536.5815 ],
       [658.0658 ],
       [342.3373 ],
       [375.47803],
       [367.70624],
       [716.30994],
       [503.86224],
       [481.49884],
       [509.60278],
       [498.30264],
       [367.05154],
       [548.6182 ],
       [489.47992],
       [574.9521 ],
       [549.4867 ],
       [485.95956],
       [504.3665 ],
       [470.77274],
       [601.8844 ],
       [443.66876],
       [582.4785 ],
       [425.29898],
       [523.17633],
       [375.93372],
       [496.35043],
       [544.88354],
       [345.39337],
       [443.7875 ],
       [640.0992 ],
       [559.5082 ],
       [538.15466],
       [606.761  ],
       [549.3295 ],
       [408.5885 ],
       [572.9263 ],
       [559.07   ],
       [521.7719 ],
       [418.82437],
       [724.71246],
       [525.9975 ],
       [533.5406 ],
       [517.0212 ],
       [452.77332],
       [527.1466 ],
       [526.42816],
       [587.77277],
       [470.41174],
       [382.85147],
       [625.6875 ],
       [805.9557 ],
       [528.8694 ],
       [662.45245],
       [540.50385],
       [494.12122],
       [541.93024],
       [551.7127 ],
       [369.8979 ],
       [642.6327 ],
       [472.0525 ],
       [479.60355],
       [509.5251 ],
       [561.52814],
       [337.24332],
       [555.1705 ],
       [545.13904],
       [439.3273 ],
       [593.2984 ],
       [559.36847],
       [425.38123],
       [462.2959 ],
       [668.7607 ],
       [400.06973],
       [554.11774],
       [335.10367],
       [447.9929 ],
       [606.4973 ],
       [542.38306],
       [455.66293],
       [444.27234],
       [355.7416 ],
       [481.6141 ],
       [385.1743 ],
       [661.03064],
       [383.93875],
       [553.0762 ],
       [567.5062 ],
       [364.70746],
       [400.80038],
       [500.98254],
       [550.4701 ],
       [567.05206],
       [731.724  ],
       [541.9869 ],
       [612.9924 ],
       [617.59454],
       [619.7193 ],
       [538.82495],
       [499.1706 ],
       [520.83563],
       [579.1581 ],
       [434.84103],
       [607.6164 ],
       [416.17676],
       [358.4077 ],
       [433.83563],
       [407.41885],
       [491.94873],
       [484.15976],
       [400.21826],
       [479.7444 ],
       [413.39304],
       [332.63388],
       [586.1744 ],
       [491.07858],
       [396.10263],
       [412.42468],
       [558.38336],
       [479.06927],
       [459.33902],
       [537.8415 ],
       [541.85095],
       [565.9102 ],
       [504.35724],
       [511.42953],
       [384.6417 ],
       [557.92285],
       [588.61786],
       [592.21295],
       [431.00668],
       [561.5147 ],
       [386.87256],
       [470.3193 ],
       [647.2369 ],
       [627.6417 ],
       [507.92136],
       [608.09   ],
       [607.248  ],
       [580.0486 ],
       [464.04416],
       [662.1826 ],
       [351.95898],
       [491.06635],
       [544.71765],
       [527.5991 ],
       [576.6907 ],
       [646.049  ],
       [492.2432 ],
       [488.95   ],
       [504.37997],
       [353.21475],
       [484.34305],
       [553.48047],
       [464.05887],
       [599.8784 ],
       [568.0219 ],
       [458.45935],
       [447.41434],
       [455.60944],
       [529.50006],
       [391.70853],
       [510.64206],
       [470.30014],
       [349.2763 ],
       [542.6755 ],
       [397.72046],
       [622.6571 ],
       [646.3552 ],
       [413.66867],
       [465.1488 ],
       [497.55658],
       [460.80008],
       [398.20264],
       [621.2637 ],
       [525.0857 ],
       [638.97034],
       [341.02872],
       [436.7121 ],
       [466.4966 ],
       [334.02322],
       [390.19247],
       [541.53705],
       [505.99753],
       [503.5501 ],
       [480.1879 ],
       [503.11484],
       [516.83484],
       [363.1268 ],
       [433.01535],
       [517.10205],
       [504.2379 ],
       [549.0682 ],
       [446.02707],
       [455.51114],
       [583.82855],
       [482.74655],
       [502.7039 ],
       [459.2126 ]], dtype=float32)

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
r2_score(ytest,yp)    #r2_score range is 0 to 1. close to 0 is good, close to 1 bad.

0.9619084651658435